#!/usr/bin/env python3
"""types.txt -> encoding/bendssz/registry.go (the id <-> Go type table)."""
import sys
rows = []
for line in open(sys.argv[1]):
    line = line.split('#')[0].strip()
    if line:
        i, name, go = line.split()
        rows.append((int(i), name, go))
o = ['// Code generated by bendssz/gen_registry.py from bendssz/types.txt. DO NOT EDIT.',
     '',
     '//go:build bendssz', '',
     'package bendssz', '',
     'import (',
     '\tenginev1 "github.com/OffchainLabs/prysm/v7/proto/engine/v1"',
     '\teth "github.com/OffchainLabs/prysm/v7/proto/prysm/v1alpha1"',
     ')', '',
     '// table maps the bend-ssz dispatcher ids to the Prysm types they decode into.',
     'var table = []struct {',
     '\tid    uint32',
     '\tname  string',
     '\tproto any',
     '}{']
for i, n, g in rows:
    o.append(f'\t{{{i}, "{n}", &{g}{{}}}},')
o.append('}')
open(sys.argv[2], 'w').write('\n'.join(o) + '\n')
