// Code generated by bendssz/gen_registry.py from bendssz/types.txt. DO NOT EDIT.

//go:build bendssz

package bendssz

import (
	enginev1 "github.com/OffchainLabs/prysm/v7/proto/engine/v1"
	eth "github.com/OffchainLabs/prysm/v7/proto/prysm/v1alpha1"
)

// table maps the bend-ssz dispatcher ids to the Prysm types they decode into.
var table = []struct {
	id    uint32
	name  string
	proto any
}{
	{0, "AttestationData", &eth.AttestationData{}},
	{1, "Checkpoint", &eth.Checkpoint{}},
	{2, "BeaconBlockHeader", &eth.BeaconBlockHeader{}},
	{3, "SignedBeaconBlockHeader", &eth.SignedBeaconBlockHeader{}},
	{4, "Validator", &eth.Validator{}},
	{5, "Attestation", &eth.AttestationElectra{}},
	{6, "SingleAttestation", &eth.SingleAttestation{}},
	{7, "AggregateAndProof", &eth.AggregateAttestationAndProofElectra{}},
	{8, "SignedAggregateAndProof", &eth.SignedAggregateAttestationAndProofElectra{}},
	{9, "SyncCommitteeMessage", &eth.SyncCommitteeMessage{}},
	{10, "SyncAggregate", &eth.SyncAggregate{}},
	{11, "ContributionAndProof", &eth.ContributionAndProof{}},
	{12, "SignedContributionAndProof", &eth.SignedContributionAndProof{}},
	{13, "BeaconBlockBody", &eth.BeaconBlockBodyElectra{}},
	{14, "BeaconBlock", &eth.BeaconBlockElectra{}},
	{15, "SignedBeaconBlock", &eth.SignedBeaconBlockFulu{}},
	{16, "DataColumnSidecar", &eth.DataColumnSidecar{}},
	{17, "BeaconState", &eth.BeaconStateFulu{}},
	{18, "IndexedAttestation", &eth.IndexedAttestationElectra{}},
	{19, "AttesterSlashing", &eth.AttesterSlashingElectra{}},
	{20, "ProposerSlashing", &eth.ProposerSlashing{}},
	{21, "SignedVoluntaryExit", &eth.SignedVoluntaryExit{}},
	{22, "Deposit", &eth.Deposit{}},
	{23, "DepositData", &eth.Deposit_Data{}},
	{24, "Eth1Data", &eth.Eth1Data{}},
	{25, "ExecutionPayload", &enginev1.ExecutionPayloadDeneb{}},
	{26, "ExecutionRequests", &enginev1.ExecutionRequests{}},
	{27, "Withdrawal", &enginev1.Withdrawal{}},
	{28, "SignedBLSToExecutionChange", &eth.SignedBLSToExecutionChange{}},
	{29, "PendingDeposit", &eth.PendingDeposit{}},
	{30, "PendingPartialWithdrawal", &eth.PendingPartialWithdrawal{}},
	{31, "PendingConsolidation", &eth.PendingConsolidation{}},
	{32, "Fork", &eth.Fork{}},
	{33, "SyncCommittee", &eth.SyncCommittee{}},
	{34, "HistoricalSummary", &eth.HistoricalSummary{}},
	{35, "ExecutionPayloadHeader", &enginev1.ExecutionPayloadHeaderDeneb{}},
}
